repository:
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
labels:
  - name: "Feature Request"
    color: "fbca04"
  - name: "Bug"
    color: "b60205"
  - name: "Wont Fix"
    color: "ffffff"
  - name: "Enhancement"
    color: a2eeef
  - name: "Documentation"
    color: "008672"
  - name: "Stale"
    color: "930191"