site_name: HACS
site_description: Home Assistant Community Store
repo_url: https://github.com/custom-components/hacs
site_url: https://custom-components.github.io/hacs
plugins: []
markdown_extensions:
    - toc:
        permalink: true
        baselevel: 1
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
  - Home: index.md
  - Installation: 
      - Manual: installation/manual.md
      - Terminal: installation/terminal.md
      - Configuration: installation/configuration.md
  - Usage:
      - Overview: usage/overview.md
      - Store: usage/store.md
      - Settings: usage/settings.md
      - Repository: usage/repository.md
      - Gallery: usage/gallery.md
  - FAQ: faq.md
  - Developer?: 
      - General: developer/general.md
      - AppDaemon developer: developer/appdaemon.md
      - Integration developer: developer/integration.md
      - Plugin developer: developer/plugin.md
      - python_script developer: developer/python_script.md
      - Theme developer: developer/theme.md
      - Include default repositories: developer/include_default_repositories.md
      - Blacklist a Repository: developer/blacklist_repository.md
  - Issues: https://github.com/custom-components/hacs/issues
