blank_issues_enabled: false
contact_links:
  - name: Closed issues for next release
    url: https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext
    about: Se closed issues that will be a part of the next release
  - name: How to file an issue
    url: https://hacs.xyz/docs/issues
    about: Describes what an issue should contain
  - name: HACS Documentation
    url: https://hacs.xyz/
    about: The documentation for HACS
  - name: HACS Discord server
    url: https://discord.gg/apgchf8
    about: For questions about HACS
