blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/hacs/integration/discussions
    about: Suggest an idea for this project
  - name: How to file an issue/feature request
    url: https://hacs.xyz/docs/issues
    about: Describes what an issue/feature request should contain
  - name: HACS Documentation
    url: https://hacs.xyz/
    about: The documentation for HACS
  - name: HACS Discord server
    url: https://discord.gg/apgchf8
    about: For questions about HACS
