install:
  description: This is NOT intended to be used here, this is intended for developers!
  fields:
    repository:
      description: The repository ID
      example: '"123456789"'
register:
  description: This is NOT intended to be used here, this is intended for developers!
  fields:
    repository:
      description: The full name of the repository
      example: 'developer/repo'
    repository_type:
      description: The repository type
      example: 'plugin'