name: Backend

on:
  pull_request:
    branches:
      - master

jobs:
  ha_test:
    name: Home Assistant Check
    strategy:
      matrix:
        python-version: [
          3.6,
          3.7,
          # Python 3.8 can not yet be enabled. https://github.com/actions/setup-python/issues/30
          #3.8
          ]
        ha-version: ["stable", "beta", "dev"]
    runs-on: ubuntu-latest
    steps:
    - name: "Get the repository content"
      uses: actions/checkout@v1

    - name: Enable version ${{ matrix.python-version }} of Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel colorlog==4.0.2

    - name: Install dependencies for custom_components
      run: |
        for file in $(find custom_components/ -name "manifest.json"); do
          cat "$file" | for req in $(jq .requirements[]);
            do pip install $(echo "$req" | jq -r .);
            done;
          done

    - name: Install Home Assistant ${{ matrix.ha-version }}
      run: |
        if [ ${{ matrix.ha-version }} == "dev" ]; then
          pip install git+git://github.com/home-assistant/home-assistant.git@dev
        elif [ ${{ matrix.ha-version }} == "beta" ]; then
          pip install --pre homeassistant
        else
           pip install homeassistant
        fi

    - name: 'Copy sample configuration for Home Assistant'
      run: cp -f .devcontainer/sample_configuration.yaml ./configuration.yaml

    - name: Home Assistant configuration check
      run: |
        echo "Testing with this configuration:"
        cat configuration.yaml
        echo ""
        hass --script check_config --config .