name: "HACS Actions"

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, closed]

jobs:
  test:
    name: Automation
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/actions@master
        name: HACS Actions
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"