name: Home Assistant

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ha_test:
    name: Home Assistant Check
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v2

      - name: ğŸ› ï¸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ“¦ Install dependencies
        run: |
          make init


      - name: ğŸ“¦ Install dependencies for custom_components
        run: |
          for file in $(find custom_components/ -name "manifest.json"); do
            cat "$file" | for req in $(jq .requirements[]);
              do pip install $(echo "$req" | jq -r .);
              done;
            done

      - name: ğŸ“‹ Copy sample configuration for Home Assistant
        run: |
          cp -f .devcontainer/sample_configuration.yaml ./configuration.yaml
          sed -i 's/#//g' ./configuration.yaml

      - name: ğŸƒ Run Home Assistant configuration check
        run: |
          echo "Testing with this configuration:"
          cat configuration.yaml
          echo ""
          hass --script check_config --config .