name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1


      # Get updated translations
      - name: Download Lokalise CLI
        run: |
          curl -sSL \
            "https://s3-eu-west-1.amazonaws.com/lokalise-assets/cli/lokalise-0.721-linux-amd64.tgz" \
            -o ./lokalise.tgz
          tar -xvzf ./lokalise.tgz
      - name: Downloading translations
        run: |
          ./lokalise \
              --token "${{ secrets.lokalise_token }}" \
              export "190570815d9461966ae081.06523141" \
              --type json \
              --unzip_to  /tmp/lokalise \
              --filter reviewed \
              --export_empty skip \

              --export_sort a_z
      - name: Clear current translations
        run: |
          rm /home/runner/work/integration/integration/custom_components/hacs/.translations/*
      - name: Move new  translations
        run: |
          cp /tmp/lokalise/locale/* /home/runner/work/integration/integration/custom_components/hacs/.translations/

      # Download frontend
      - name: Clone frontend
        run: |
          git clone https://github.com/hacs/frontend.git

      # Build Frontend
      - name: Build the HACS frontend
        run: |
          cd /home/runner/work/integration/integration/frontend
          npm install
          npm run build

      # Build Frontend
      - name: Move the HACS frontend file
        run: |
          cd /home/runner/work/integration/integration
          cp -f /home/runner/work/integration/integration/frontend/build/main.js.gz /home/runner/work/integration/integration/custom_components/hacs/frontend/experimental/main.js.gz

      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ github.ref }}"' /home/runner/work/integration/integration/custom_components/hacs/const.py
          sed -i 's|refs/heads/||' /home/runner/work/integration/integration/custom_components/hacs/const.py
          sed -i 's|refs/tags/||' /home/runner/work/integration/integration/custom_components/hacs/const.py

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP HACS Dir
        run: |
          cd /home/runner/work/integration/integration/custom_components/hacs
          zip hacs.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/integration/integration/custom_components/hacs/hacs.zip
          asset_name: hacs.zip
          tag: ${{ github.ref }}
          overwrite: true