name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.check }}
    strategy:
      matrix:
        check:
          - pyupgrade
          - black
          - codespell
          - check-executables-have-shebangs
          - check-json
          - requirements-txt-fixer
          - check-ast
          - mixed-line-ending
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: ğŸ› ï¸ Set up Python
        uses: actions/setup-python@v4.5.0
        id: python
        with:
          python-version: "3.x"

      - name: ğŸ“¦ Install pre-commit
        run: |
          scripts/install/pip_packages pre-commit
          pre-commit install-hooks --config .github/pre-commit-config.yaml

      - name: ğŸƒ Run the check (${{ matrix.check }})
        run: pre-commit run --hook-stage manual ${{ matrix.check }} --all-files --config .github/pre-commit-config.yaml

  lint-custom:
    runs-on: ubuntu-latest
    name: With bellybutton
    steps:
    - name: ğŸ“¥ Checkout the repository
      uses: actions/checkout@v3.3.0

    - name: ğŸ› ï¸ Set up Python
      uses: actions/setup-python@v4.5.0
      id: python
      with:
        python-version: "3.x"
        cache: 'pip'
        cache-dependency-path: |
          requirements_base.txt
          requirements_lint.txt

    - name: ğŸ“¦ Install requirements
      run: scripts/install/pip_packages --requirement requirements_lint.txt

    - name: âœ… Add problem matcher
      run: echo "::add-matcher::.github/matchers/bellybutton.json"

    - name: ğŸƒ Run validation
      run: bellybutton lint

  lint-json:
    runs-on: ubuntu-latest
    name: With JQ
    steps:
    - name: ğŸ“¥ Checkout the repository
      uses: actions/checkout@v3.3.0

    - name: ğŸƒ Run validation
      run: jq -r -e -c . tests/fixtures/*.json