name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  matrix:
    runs-on: ubuntu-latest
    name: Run ${{ matrix.check }}
    strategy:
      matrix:
        check:
          - check-ast
          - check-executables-have-shebangs
          - check-json
          - codespell
          - isort
          - mixed-line-ending
          - pyupgrade
          - requirements-txt-fixer
          - ruff-check
          - ruff-format
    steps:
      - name: Checkout the repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        id: python
        with:
          python-version: "3.13"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_lint.txt

      - name: Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_lint.txt
          pre-commit install-hooks --config .github/pre-commit-config.yaml

      - name: Run the check (${{ matrix.check }})
        run: pre-commit run --show-diff-on-failure --hook-stage manual ${{ matrix.check }} --all-files --config .github/pre-commit-config.yaml

  lint-json:
    runs-on: ubuntu-latest
    name: With JQ
    steps:
    - name: Checkout the repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Run validation
      run: jq -r -e -c . tests/fixtures/*.json