name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release_zip_file:
    name: Publish HACS zip file asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: ğŸ› ï¸ Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"

      - name: ğŸ”¢ Get version
        if: ${{ github.event_name == 'release' }}
        id: version
        uses: home-assistant/actions/helpers/version@01a62fa0b7ab4a0ac894184f48a82477812dca4b # master

      - name: ğŸ”¢ Set version number
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -i "/MINIMUM_HA_VERSION = /c\MINIMUM_HA_VERSION = \"$(jq .homeassistant -r ${{ github.workspace }}/hacs.json)\"" ${{ github.workspace }}/custom_components/hacs/const.py
          python3 ${{ github.workspace }}/scripts/update/manifest.py --version ${{ steps.version.outputs.version }}

      - name: â¬ Download HACS frontend
        run: ${{ github.workspace }}/scripts/install/frontend

      - name: ğŸ“¤ Upload zip to action
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: ${{ github.event_name == 'push' }}
        with:
          name: hacs
          path: ${{ github.workspace }}/custom_components/hacs
          retention-days: 7

      # Pack the HACS dir as a zip and upload to the release
      - name: ğŸ“¦ ZIP HACS Dir
        if: ${{ github.event_name == 'release' }}
        run: |
          cd ${{ github.workspace }}/custom_components/hacs
          zip hacs.zip -r ./

      - name: ğŸ“¤ Upload zip to release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/hacs/hacs.zip

