name: Publish

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  release_zip_file:
    name: Publish HACS zip file asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set version number"
        run: |
          sed -i "/MINIMUM_HA_VERSION = /c\MINIMUM_HA_VERSION = \"$(jq .homeassistant -r ${{ github.workspace }}/hacs.json)\"" ${{ github.workspace }}/custom_components/hacs/const.py
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}

      - name: Add download HACS frontend
        run: ${{ github.workspace }}/manage/install_frontend

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP HACS Dir
        run: |
          cd ${{ github.workspace }}/custom_components/hacs
          zip hacs.zip -r ./

      - name: Upload zip to action
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: hacs.zip
          path: ${{ github.workspace }}/custom_components/hacs/hacs.zip

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        if: ${{ github.event_name == 'release' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/hacs/hacs.zip
          asset_name: hacs.zip
          tag: ${{ github.ref }}
          overwrite: true
