name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release_zip_file:
    name: Publish HACS zip file asset
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: ğŸ› ï¸ Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.x"

      - name: ğŸ”¢ Get version
        if: ${{ github.event_name == 'release' }}
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: ğŸ”¢ Set version number
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -i "/MINIMUM_HA_VERSION = /c\MINIMUM_HA_VERSION = \"$(jq .homeassistant -r ${{ github.workspace }}/hacs.json)\"" ${{ github.workspace }}/custom_components/hacs/const.py
          python3 ${{ github.workspace }}/scripts/update/manifest.py --version ${{ steps.version.outputs.version }}

      - name: â¬ Download HACS frontend
        run: ${{ github.workspace }}/scripts/install/frontend

      - name: ğŸ“¤ Upload zip to action
        uses: actions/upload-artifact@v3.1.2
        if: ${{ github.event_name == 'push' }}
        with:
          name: hacs
          path: ${{ github.workspace }}/custom_components/hacs
          retention-days: 7

      # Pack the HACS dir as a zip and upload to the release
      - name: ğŸ“¦ ZIP HACS Dir
        if: ${{ github.event_name == 'release' }}
        run: |
          cd ${{ github.workspace }}/custom_components/hacs
          zip hacs.zip -r ./

      - name: ğŸ“¤ Upload zip to release
        uses: softprops/action-gh-release@v0.1.15
        if: ${{ github.event_name == 'release' }}
        with:
          files: ${{ github.workspace }}/custom_components/hacs/hacs.zip

