name: "HACS: Pull request action"
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/hacs-actions@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          action: "PullLabler"