name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:
    name: With pytest for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10"]
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: ğŸ› ï¸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: ğŸ“¦ Install dependencies
        run: |
          make init
          python3 -m pip install pytest pytest-cov

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest

      - name: ğŸ“¤ Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          make coverage
          curl -sfSL https://codecov.io/bash | bash -

  legacy:
    name: With pytest with Home Assistant 2022.10.0
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.0.2

      - name: ğŸ› ï¸ Set up Python 3.9
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.9"
          cache: 'pip'

      - name: ğŸ“¦ Install dependencies
        run: |
          make init
          python3 -m pip install pytest pytest-cov
          make homeassistant-install-old

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest
