name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: With pytest for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: ğŸ› ï¸ Set up Python
        uses: actions/setup-python@v4.5.0
        id: python
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install requirements
        run: |
          scripts/install/frontend
          scripts/install/pip_packages --requirement requirements_test.txt

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest

      - name: ğŸ“¤ Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          scripts/coverage
          curl -sfSL https://codecov.io/bash | bash -

  legacy:
    name: With pytest with Home Assistant 2022.11.0
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v3.3.0

      - name: ğŸ› ï¸ Set up Python 3.9
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.9"
          cache: 'pip'
          cache-dependency-path: |
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_test.txt
          scripts/install/core
          scripts/install/frontend

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: |
          python3 -m pytest
