name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  legacy:
    name: With pytest with Home Assistant (min. supported version)
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: ğŸ› ï¸ Set up Python 3.12
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: |
            requirements_core_min.txt
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install dependencies
        run: |
          scripts/install/pip_packages \
            --requirement requirements_core_min.txt \
            --requirement requirements_test.txt
          scripts/install/frontend

      - name: â²ï¸ Set time zone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Asia/Singapore'

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: scripts/test

  dev:
    name: With pytest with Home Assistant (${{ matrix.homeassistant-version }}) & Python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        homeassistant-version:
          - "dev"
        python-version:
          - "3.12"
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: ğŸ› ï¸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements_core_min.txt
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_test.txt
          scripts/install/core_dev
          scripts/install/frontend

      - name: â²ï¸ Set time zone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: 'Asia/Singapore'

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: scripts/test

      - name: ğŸ“¤ Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          scripts/coverage
          curl -sfSL https://codecov.io/bash | bash -