name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  legacy:
    name: With pytest with Home Assistant (min. supported version)
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: ğŸ› ï¸ Set up Python 3.13
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"
          cache: 'pip'
          cache-dependency-path: |
            requirements_core_min.txt
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install dependencies
        run: |
          scripts/install/pip_packages \
            --requirement requirements_core_min.txt \
            --requirement requirements_test.txt
          scripts/install/frontend

      - name: â²ï¸ Set time zone
        uses: szenius/set-timezone@1f9716b0f7120e344f0c62bb7b1ee98819aefd42 # v2.0
        with:
          timezoneLinux: 'Asia/Singapore'

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: scripts/test

  dev:
    name: With pytest with Home Assistant (${{ matrix.homeassistant-version }}) & Python (${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        homeassistant-version:
          - "dev"
        python-version:
          - "3.13"
          - "3.14"
    steps:
      - name: ğŸ“¥ Checkout the repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: ğŸ› ï¸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            requirements_core_min.txt
            requirements_base.txt
            requirements_test.txt

      - name: ğŸ“¦ Install dependencies
        run: |
          scripts/install/pip_packages --requirement requirements_test.txt
          scripts/install/core_dev
          scripts/install/frontend

      - name: â²ï¸ Set time zone
        uses: szenius/set-timezone@1f9716b0f7120e344f0c62bb7b1ee98819aefd42 # v2.0
        with:
          timezoneLinux: 'Asia/Singapore'

      - name: ğŸƒ Run tests
        env:
          PYTEST: true
        run: scripts/test

      - name: ğŸ“¤ Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.13' }}
        run: |
          scripts/coverage
          curl -sfSL https://codecov.io/bash | bash -