name: 'Close stale issues'

on:
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *'

permissions: {}

jobs:
  issues_missing_required_information:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f  # v10.2.0
        with:
          days-before-stale: -1
          days-before-close: 7
          only-labels: 'Missing required issue information'
          stale-issue-label: 'Missing required issue information'
